language: go

go:
  - 1.6

# Submodule fix: https://gist.github.com/iedemam/9830045
git:
  submodules: false

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - go get github.com/modocache/gover

before_script:
  - wget https://s3.amazonaws.com/influxdb/influxdb_0.10.3-1_amd64.deb
  - sudo dpkg -i influxdb_0.10.3-1_amd64.deb
  - sudo service influxdb start

after_success:
  - bash <(curl -s https://codecov.io/bash)
